language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"

install:
  - composer install --dev
  - composer show -i
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:

script:
  - ./vendor/bin/php-cs-fixer fix -v --dry-run src;
  - ./vendor/bin/php-cs-fixer fix -v --dry-run tests;
  - ./vendor/bin/phpunit

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/log/clover.xml

matrix:
  fast_finish: true
